### ISSUE TITLE
doesn't work on NYTimes

### ISSUE THREAD

**Issue by jiangts** [fczbkk/css-selector-generator#13]
Failed on this page: http://www.nytimes.com/2016/01/14/fashion/nest-thermostat-glitch-battery-dies-software-freeze.html

Clicking on the links or the menubar will cause Chrome to run out of memory and display an "Aw, Snap" page.

Not sure what the bug is... I switched to dompath and it worked though.

**Comment by venkatkarun** [comment]
Fails on http://www1.folha.uol.com.br/poder/2016/03/1746871-oposicao-mira-em-dilma-para-evitar-vitimizacao-de-lula.shtml with "Aw, Snap". optimal-select returned a valid result.

**Comment by eazuka** [comment]
@fczbkk Thanks for this awesome css selector generator. Its seem like this issue and issues #16, #20 are facing same problem. Are you close to getting a solution?

**Comment by fczbkk** [comment]
@eazuka I have some ideas about how to fix this and make the selector generator better, but it would require a larger rewrite of the library. I'd like to do it during the summer.

**Comment by tomgallagher** [comment]
Any updates on the rewrite? I'm still struggling on elements with large numbers of classes. I'd take the classes out as an option but I then have another problem with multiple nth-child selectors elsewhere. 

I was thinking that, just getting it to throw an error if it locks up, would enable me to kill it and launch without classes when I absolutely have to. Would you have any suggestions on where I might put a throw statement to deal with the getCombinations() issue?

Thanks for the tool, anyway, even if you're too busy to deal with this. I'm using it and it's working fine, I'm just having to run a blacklist of sites where it won't deal with classes.

**Comment by Azwartmaks** [comment]
try do next
```
			ref = items.length - 1;
			ref1 = result.length - 1;
			for (i = 0; 0 <= ref ? i <= ref : i >= ref; i = 0 <= ref ? ++i : --i) {
				for (j = 0; 0 <= ref1 ? j <= ref1 : j >= ref1; j = 0 <= ref1 ? ++j : --j) {
					result.push(result[j].concat(items[i]));
				}
			}
```
