### ISSUE TITLE
Can't use sanitizeSelectorItem anymore in version 3.4.4

### ISSUE THREAD

**Issue by mika-cn** [fczbkk/css-selector-generator#136]
I currently use version 2.1.0 and trying to upgrate to the latest version. In latest version the `sanitizeSelectorItem` function is not exported anymore.

The code i'm using is:

```javascript
import {sanitizeSelectorItem} from 'css-selector-generator/src/utilities-selectors.js'
```

That file (src/utilities-selectors.js) has become a Type Script file which I can't import anymore.

**Comment by fczbkk** [comment]
Hey @mika-cn. That was an internal utility function and it was not supposed to be used like that.

You should use browser's native method `CSS.escape()`:
https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape

If you need to support legacy browsers, you can use this polyfill:
https://github.com/mathiasbynens/CSS.escape/blob/master/css.escape.js

**Comment by mika-cn** [comment]
Thank you for the really helpful reply. It seems like a better way to rely on browser's APIs. I'll try it.
