### ISSUE TITLE
Attribute css selector test error. 

### ISSUE THREAD

**Issue by fivesmallq** [fczbkk/css-selector-generator#15]
Demo url : https://jsfiddle.net/fivesmallq/amfw7vtm/3/

![image](https://cloud.githubusercontent.com/assets/745063/13460077/342694f4-e0b3-11e5-9e53-4a517ee759b8.png)

In the HTML `querySelectorAll` function, `[width=30%]` is wrong, `[width="30%"]` is right. 

https://github.com/fczbkk/css-selector-generator/blob/7624f0b6f2b0124abb667ae424f3c261395faba4/build/css-selector-generator.js#L114

Maybe you should retain the double quotes? 

``` javascript
    CssSelectorGenerator.prototype.getAttributeSelectors = function(element) {
      var attribute, blacklist, k, len, ref, ref1, result;
      result = [];
      blacklist = ['id', 'class'];
      ref = element.attributes;
      for (k = 0, len = ref.length; k < len; k++) {
        attribute = ref[k];
        if (ref1 = attribute.nodeName, indexOf.call(blacklist, ref1) < 0) {
          result.push("[" + attribute.nodeName + "=\"" + attribute.nodeValue + "\"]");
        }
      }
      return result;
    };
```

**Comment by fczbkk** [comment]
The attribute selectors should now be properly quoted and escaped:
https://github.com/fczbkk/css-selector-generator/blob/master/test/selector-attribute.spec.js#L104-L108
