### ISSUE TITLE
Large amount of classes locks up getCombinations

### ISSUE THREAD

**Issue by bryanlb** [fczbkk/css-selector-generator#16]
I'm seeing an issue where a website with a large amount of classes on the `<html>` element causes the `getCombinations` to lock up on the following code:

```
for (i = k = 0, ref = items.length - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
  for (j = l = 0, ref1 = result.length - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
    result.push(result[j].concat(items[i]));
  }
}
```

In my case, I have 47 classes that are returned by `getAllSelectors`, which I assume are generated by the UI libraries running on the website.

**Comment by bryanlb** [comment]
Looks like this is probably the same issue as #13 - both of the referenced sites have large amounts of classes on topmost element.

**Comment by fczbkk** [comment]
@bryanlb Thanks for the analysis. I'll have to dive into combinatorics and find out some more effective way to do this.

**Comment by rcowin** [comment]
@fczbkk I ran into this with 33 classes - I am restricting items to 6 elements giving me only 64 combinations to work around this. I am sure you are close to a resolution, but with all the tools out there it seems difficult to be smart about class selection (smart attribute selection would be quite a bit easier though). 

Perhaps a strategy that uses a combinatorics for the first few (5-7) and then just adds the others as a single value? However, I suspect that large number of classes implies that they would be fairly volatile over time. Perhaps a heuristic like sorting smallest class names first might help the arbitrariness of the class names.

**Comment by vishaltelangre** [comment]
My browser was also running out of memory when I tried to grab the selectors on nytimes website.

Until this is fixed, I am getting rid of the classes added on `HTML` tag with the following condition:

```js
// ...
CssSelectorGenerator.prototype.getClassSelectors = function(element) {
      var class_string, item, result;
      result = [];

      if (element.tagName === 'HTML') {
        return result;
      }

     // ...
```

**Comment by fczbkk** [comment]
I have added [`maxCombinations`](https://github.com/fczbkk/css-selector-generator#max-combinations) and [`maxCandidates`](https://github.com/fczbkk/css-selector-generator#max-candidates) performance options. These should help to deal with the sites that, for example, use large number of classnames on elements.
