### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by abhishek-anand** [fczbkk/css-selector-generator#19]
This works fine for most cases but breaks down with an error for some elements with "Uncaught TypeError: Cannot read property 'querySelectorAll' of null"

<img width="1273" alt="screen shot 2016-05-23 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/2356550/15466452/58c14cc6-20f7-11e6-9f90-f62eb60eabd3.png">

The error in my case came when using this on this page https://cloud.digitalocean.com/droplets/new?size=2gb&region=nyc2 and clicking on a div in "Choose a datacenter region".

**Comment by yyl21** [comment]
I got the same error. TypeError: Cannot read property 'querySelectorAll' of null

`export function getNthOfTypeSelector (element) {
  const tag = getTagSelector(element)[0];
  const siblings = element.parentElement.querySelectorAll(tag);
  for (let i = 0; i < siblings.length; i++) {
    if (siblings[i] === element) {
      return [`${tag}:nth-of-type(${i + 1})`];
    }
  }
  return [];
}`

Should 'parentElement' be replaced by 'parentNode'?  Could you please solve this problem? @fczbkk

**Comment by fczbkk** [comment]
@yyl21 Thanks for reminding me of this bug.

I have updated the `nth-of-type` selector generator so that it checks for the element's parent existence. It should now not throw an error either when evaluating element outside of a document, or a root element (e.g. `HTML`).

Please update the library to `v2.1.1` to apply this fix.

**Comment by webpolis** [comment]
This bug still occurs using v2.1.1

Test it here: https://es.wikipedia.org/wiki/Biopel%C3%ADcula

And click on any of the pictures at the bottom.
