### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [fczbkk/css-selector-generator#2]
I'm looking for a library to generate unique CSS selectors for DOM elements in an arbitrary page (see [1](http://stackoverflow.com/questions/4588119/get-elements-css-selector-without-element-id/4588287#4588287), [2](http://stackoverflow.com/questions/8588301/how-to-generate-unique-css-selector-for-dom-element), [3](http://stackoverflow.com/questions/2068272/getting-a-jquery-selector-for-an-element), [4](http://stackoverflow.com/questions/5706837/get-unique-selector-of-element-in-jquery)).

In case you [looked at existing alternatives before coding a new one from scratch](https://slides.com/dandv/prior-art), how does this library compare with @martinsbalodis's [css-selector](https://github.com/martinsbalodis/css-selector), which started development before this one and even has almost the same name, which suggests you might have searched for it.

**Comment by fczbkk** [comment]
This is an interesting question. I'll try to do a benchmark to compare various similar libraries.

Here's the list from your other issue (#3):

* @martinsbalodis's [css-selector](2)
* @tildeio's https://github.com/tildeio/selector-generator
* @jhartikainen's https://github.com/jhartikainen/dompath (has tests)
* @olivierrr's https://www.npmjs.com/package/selector-query (simple)
* @rishihahs's https://www.npmjs.com/package/domtalk (simple)
* @thomaspeklak's https://www.npmjs.com/package/get-query-selector (very simple)
* @stevoland's https://github.com/stevoland/CSSelector.js (quite simple)
* @ngs's https://www.npmjs.com/package/jquery-selectorator (jQuery)
* @bimech's https://github.com/bimech/ellocate.js (jQuery)
* @desmondw's [snowflake](https://github.com/desmondw/snowflake/blob/master/js/inject.js#L55) for Chrome

**Comment by fczbkk** [comment]
This was fun: https://github.com/fczbkk/css-selector-generator-benchmark

**Comment by dandv** [comment]
Forgot to mention [Chromium's take on it](https://github.com/fczbkk/css-selector-generator-benchmark/issues/2).

**Comment by dandv** [comment]
BTW, thanks again for your work on this. I've posted an [answer on this SO question](http://stackoverflow.com/questions/2068272/getting-a-jquery-selector-for-an-element/32218234#32218234), trying to create awareness that generating unique and relatively robust selectors is a non-trivial problem.
