### ISSUE TITLE
CSS selector generator silently failing on some sites

### ISSUE THREAD

**Issue by tomgallagher** [fczbkk/css-selector-generator#20]
Hi - me again (sorry).

I'm running this bit of code in the console

`document.addEventListener( "mouseover", function(event) { var CSSstring = findCSSPath(event.target); console.log(CSSstring); });`

where the findCSSPath function is just a wrapper for your css selector generator.

On the whole, this works as expected. I've tested it on quite a few sites. However, on 

`http://observer.com/`

I'm getting a silent failure from the code. No errors, but no CSS path sent to the console. Eventually it causes Chrome to crash. There's clearly something odd about the structure of the site.

I don't know if this is the kind of thing you want reported, but I'm struggling to find the problem.

**Comment by tomgallagher** [comment]
I've been doing a bit more digging on this silent failure problem.  It seems like all the problem sites I have encountered show this line in the console on load:

`JQMIGRATE: Migrate is installed, version 1.4.0`

This probably isn't the cause, but it is an indicator that all of the problems I have encountered so far have been with sites that have been put together by WordPress. I'm not familiar with WordPress myself, but their sites seems to be very heavy on class names, often extending to 10 lines in the browser.

Again, I don't know if I'm helping here but I thought I should pass the info along.

Other examples I mentioned:

`http://theberry.com/`

`http://rickeysmileymorningshow.com/`

`http://allfordiva.com/`

cheers

**Comment by fczbkk** [comment]
@tomgallagher Thank you for your research. It seems that these sites use some library that changes some native methods used in the CssSelectorGenerator library. I have seen similar behaviour with PrototypeJS and MooTools (they both implement their own `Array.reduce()`, which works differently than the native implementation). I'm pretty sure this will be something like that.

**Comment by oddui** [comment]
@fczbkk this is happening to me as well.

In my case there are 45 css classes on an element and `CssSelectorGenerator#getCombinations()` is going crazy and crashes the chrome tab. It needs some algorithm love.

**Comment by tomgallagher** [comment]
Hi - you probably know this: I've tried the problem sites with the class selector taken out of the options and there's no fails on the four examples I mentioned above.

**Comment by tomgallagher** [comment]
Hi - I have a more general question related to the above.

I'm not that familiar with CSS selectors. If you know that you're going to be using a modern Chrome browser, which options would you select to be the fastest and most reliable, given the class bloat that seems common these days?

In particular, I'm wondering about the attribute and nth child options. Is there a speed difference? If I just chose id and tag, would your routine still generate unique selectors? 

Which options would you choose if you had total flexibility?

**Comment by oddui** [comment]
@tomgallagher i'm not too sure about the speed difference but as the doc says `nth child` is necessary to create a unique CSS selector for every possible element. Note that if you rely too much on `nth child`, a simple change in the elements tree might just break your selector.

**Comment by fczbkk** [comment]
@tomgallagher As @oddui said, you need `nth-child` selectors to be sure to get unique selector for every element, regardless of situation.

If you are sure you will only be generating selectors for elements that can be targeted using IDs and classes, you can only enable those.

If you want the speed, then only enable `nth-child` selectors. The resulting selectors will be long and ugly. But generating the selectors will be straightforward and quick.

**Comment by fczbkk** [comment]
I have added [`maxCombinations`](https://github.com/fczbkk/css-selector-generator#max-combinations) and [`maxCandidates`](https://github.com/fczbkk/css-selector-generator#max-candidates) performance options. These should help to deal with the sites that, for example, use large number of classnames on elements.
