### ISSUE TITLE
Use  in Electron

### ISSUE THREAD

**Issue by MaharishiCanada** [fczbkk/css-selector-generator#22]
It will be nice to have some way (or documentation if it is already available)  about how to use this script in Electron . See https://github.com/electron/electron/issues/9664

**Comment by MaharishiCanada** [comment]
OK, it was easy. I found the way to use this script in a webview tag under Electron.  First, you install css-selector-generator (in my case locally in the cwd dev folder):
``` bash
npm install --save-dev  css-selector-generator
```
You add the webview tag in the renderer html file:
```
<webview  preload="preloadtest.js" src="https://github.com" ></webview>
```
Then, in the preloadtest.js script you use:
``` javascript
var CssSelectorGenerator = require('css-selector-generator').CssSelectorGenerator; 
global.myapi = {
  CssSelectorGenerator : CssSelectorGenerator 
} 
```
The `global.api` variable is used to export the constructor to the webview. Then you use the method `executeJavaScript` of the `webContents` of the webview with the following script  : 
``` javascript
    var my_selector_generator = new myapi.CssSelectorGeneratorX; 
    var my_element_selector = my_selector_generator.getSelector(adi);
    console.log(my_element_selector); 
```
These last three lines come from your documentation. That's it. I don't explain how to get this webContents object - the Electron documentation is fine on this part.

**Comment by fczbkk** [comment]
I'm sorry, I have no experience with Electron. Hopefully, future explorers will find your answer.
