### ISSUE TITLE
What is the expected value of  `this` in css-selector-generator.js ? 

### ISSUE THREAD

**Issue by MaharishiCanada** [fczbkk/css-selector-generator#23]
I am puzzle by the use of  `this` in  css-selector-generator.js.  An anonymous function is called and we fix its context with `.call(this)`.  It seems that the expectation is that the global object will be somehow aliased to the window object. It's the case with Electron. Is it a general convention that you rely upon?

**Comment by MaharishiCanada** [comment]
Ok, I just looked at the code and I see that the fixed context `this` in the called anonymous function is only the object where the constructor is exported, when `module.exports` (aliased to `exports`) is not defined.  When we use `require`,  `module.exports` is defined and thus we do not care about the value of the parameter `this` in `.call(this)` - it's not used.  Still, I am curious to know what are the use cases where this parameter is used.

**Comment by fczbkk** [comment]
I assume you are asking about this line:
https://github.com/fczbkk/css-selector-generator/blob/master/src/css-selector-generator.coffee#L224

It either adds `CssSelectorGenerator` property to the `exports` object (if it exists), or to the root object (`this` references `window` in browser and `process` in Node). So it basically either exports the library, or it adds it to the global namespace.
