### ISSUE TITLE
Infinite loops occur at some sites when creating selector strings

### ISSUE THREAD

**Issue by Pirikara** [fczbkk/css-selector-generator#274]
Although not often the case, the Array.from method is occasionally overridden on sites for Internet Explorer.
This is because Array.from is not supported in Internet Explorer.

When trying to get a selector at that site, the getPowerSet method defined in utilities-powerset.ts sometimes causes an infinite loop.

This is due to the fact that the return value of the generateOffsets method in the same file is always an empty array.

You can clone this repository and open it in your browser to see the errors.
https://github.com/Pirikara/override_array_from

Modifying the implementation in a way that does not use Array.from can solve this problem.

I am wondering if you would like to respond to this, but if you don't mind, I will create a PR for you.

Regards.

**Comment by fczbkk** [comment]
Hey @Pirikara, thanks for the report. I understand the issue and it would be easy to do the workaround. But I'm not going to do it.

I've been dealing with this crap for 20 years. Writing polyfills, hacking IE and tiptoeing around libraries that are mutating native objects. This is triggering PTSD for me.

IE is dead and native object mutating is a bad practice. It's time to stop this madness.

I will not fix this.

![6g4o0k](https://user-images.githubusercontent.com/43734/168422978-d2625fae-3999-4b68-8651-5fa847b75153.jpg)
