### ISSUE TITLE
Add package to npm

### ISSUE THREAD

**Issue by dandv** [fczbkk/css-selector-generator#3]
https://www.npmjs.com/search?q=selector+generator doesn't produce this package, which seems to be one of the best. Some others I've looked at:

* @martinsbalodis's [css-selector](2)
* @tildeio's https://github.com/tildeio/selector-generator
* @jhartikainen's https://github.com/jhartikainen/dompath (has tests)
* @olivierrr's https://www.npmjs.com/package/selector-query (simple)
* @rishihahs's https://www.npmjs.com/package/domtalk (simple)
* @thomaspeklak's https://www.npmjs.com/package/get-query-selector (very simple)
* @stevoland's https://github.com/stevoland/CSSelector.js (quite simple)
* @ngs's https://www.npmjs.com/package/jquery-selectorator (jQuery)
* @bimech's https://github.com/bimech/ellocate.js (jQuery)
* @desmondw's [snowflake](https://github.com/desmondw/snowflake/blob/master/js/inject.js#L55) for Chrome

**Comment by fczbkk** [comment]
https://www.npmjs.com/package/css-selector-generator

**Comment by dandv** [comment]
Thanks, starred.
