### ISSUE TITLE
Export Not Found by Webpack

### ISSUE THREAD

**Issue by joealden** [fczbkk/css-selector-generator#326]
When upgrading from `3.6.1` to `3.6.3`, webpack now throws an error when trying to import both a named and default import:

```
ERROR in ./index.tsx 87:13-27
export 'getCssSelector' (imported as 'getCssSelector') was not found in 'css-selector-generator' (module has no exports)
webpack 5.74.0 compiled with 1 error in 245 ms

ERROR in ./index.tsx 87:13-27
export 'default' (imported as 'getCssSelector') was not found in 'css-selector-generator' (module has no exports)
webpack 5.74.0 compiled with 1 error in 355 ms
```

Any ideas?

**Comment by fczbkk** [comment]
Hey @joealden. I have just created `css-selector-generator@3.6.4` which should fix this issue.

Hope it helps. Feel free to reopen the issue with more details if it is still broken for you.
