### ISSUE TITLE
Clearly there are common selectors, but they cannot be obtained

### ISSUE THREAD

**Issue by 82318179** [fczbkk/css-selector-generator#392]
```html
    <table>
      <tr>
        <td>a</td>
        <td>b</td>
      </tr>
      <tr>
        <td>a</td>
        <td>b</td>
      </tr>
      <tr>
        <td>a</td>
        <td>b</td>
      </tr>
    </table>
```

```javascript
let   resultCSSSelector = getCssSelector([tr,tr], { selectors: ["tag", "class", "id", "attribute", "nthchild"]});
```

I want the result is 

```
table tr 
```

but the result as follow :

```
table tr:nth-child(1), .table tr:nth-child(2)
```

 How to get the common selectors of an array instead of getting the relationship between or。

**Comment by fczbkk** [comment]
Hey @82318179. You are looking for a unique selector for **two** of the TR elements. The `table tr` selector would match **all three** TR elements in your example.

This library is for generating unique selectors for provided elements and **only** for these elements.
