### ISSUE TITLE
Hope to add multiple elements to take common css selector 

### ISSUE THREAD

**Issue by 82318179** [fczbkk/css-selector-generator#397]
```
<div class="pagebtns" style="left: 196px;">
	<label value="6">6</label>
	<label value="7">7</label>
                <label value="8" class="cur">8</label>
                <label value="9">9</label>
</div>
```

just like this label  elements ,now this css-selector-generator the selector like 

div.pagebtns label:nth-child(1), div.pagebtns label:nth-child(2), div.pagebtns label:nth-child(3), div.pagebtns label:nth-child(4)

Can you directly create a common single selector like

div.pagebtns label:nth-child(n)
or  
div.pagebtns label:nth-child(n+1)

**Comment by fczbkk** [comment]
Hey @82318179. I'm not sure I understand your question correctly. It looks like you are asking if it is possible to create a common unique selector matching multiple elements at once. Yes, that is possible, see the documentation for more details:
https://github.com/fczbkk/css-selector-generator#multi-element-selector

If I misunderstood your question, feel free to provide some context and reopen the issue.
