### ISSUE TITLE
using css-selector-generator on node with jsdom

### ISSUE THREAD

**Issue by mwotton** [fczbkk/css-selector-generator#437]
this is more to note my experience than to ask for anything, obviously this library is aimed mostly at running in the browser.

anyway, injecting it this way

```
    var dom = new jsdom.JSDOM(data, {runScripts: "outside-only", virtualConsole});
    ...
    const script = new Script(readFileSync("/home/mark/ml/yasc/tools/css-oracle/node_modules/css-selector-generator/build/index.js"));
    const vmContext = dom.getInternalVMContext();
    script.runInContext(vmContext);
```
    
    and running it with window.eval gave the error 
```
        ReferenceError: CSS is not defined
```

which seems like a known bug here:  https://github.com/jsdom/jsdom/issues/2026

If there's a virtual dom you'd recommend, please let me know - spinning up a headless browser for this on the server seems like overkill.

**Comment by fczbkk** [comment]
Hey @mwotton. JSDOM is only good for simulating DOM. Everything else is a Potemkin village. It's fine for testing React components, but if you expect it to be a simulator of a browser environment, you're going to have a hard time.

You can use a polyfill to simulate the `CSS.escape()` method. I recommend this one:
https://github.com/mathiasbynens/CSS.escape

The code that uses it all together will look something like this:

```javascript
import fs from 'node:fs/promises'
import { JSDOM } from 'jsdom';

const { window } = new JSDOM('<!DOCTYPE html><body><p id="myElement">Hello world</p></body>', { runScripts: "dangerously" });

const CssEscapePolyfill = await fs.readFile('./node_modules/css.escape/css.escape.js', 'utf-8')
const CssSelectorGeneratorLibrary = await fs.readFile('./node_modules/css-selector-generator/build/index.js', 'utf-8')

const scriptElement = window.document.createElement('script')
scriptElement.textContent = CssEscapePolyfill + CssSelectorGeneratorLibrary
window.document.body.appendChild(scriptElement)

window.eval(`
  foundCssSelector = CssSelectorGenerator.getCssSelector(document.querySelector('p'))
`);

console.log(window.foundCssSelector) // <-- '#myElement'
```

**Comment by adaboese** [comment]
I needed something that "just works" for node.js, even if it does not produce correct output 100% of the time.

I couldn't get `css-selector-generator` to work with JSDOM.

Sharing for others who stumble upon this thread.

```ts
const getElementSelector = (element: Element) => {
  const classNames = element.className
    .split(' ')
    .filter((className) => className.length > 0);

  if (classNames.length === 0) {
    return element.tagName.toLowerCase();
  }

  const cssSelector = classNames.map((className) => `.${className}`).join('');

  return `${cssSelector}`;
};

export const getCssSelector = async (element: Element) => {
  const selectors = [];

  let currentElement = element;

  while (currentElement) {
    selectors.push(getElementSelector(currentElement));

    const parentElement = currentElement.parentElement;

    if (parentElement && parentElement.tagName !== 'BODY') {
      currentElement = parentElement;
    } else {
      break;
    }
  }

  return selectors.reverse().join(' > ');
};
```

**Comment by fczbkk** [comment]
Hey @adaboese, I have checked [the example JSDOM code above](https://github.com/fczbkk/css-selector-generator/issues/437#issuecomment-1537448369) and it works fine. What problems did you experience?

The code you shared, as you mentioned, will not produce a unique CSS selector in many situations. The simplest example is this HTML structure:

```html
<div>
  <p>first</p>
  <p>second</p>
</div>
```

When looking for selector for the first paragraph, your function will produce `div > p`, which will match both paragraphs (so the result is not unique).

If you don't really care about how the CSS selector looks, as long as it works, I recommend using a chain of `nth-child` selectors connected by child combinator, all the way from the root node. This kind of selectors will always uniquely match only a single element. So the selector for the example above will look something like this: `:root > :nth-child(1) > :nth-child(1)`.

Here's the code that will produce these selectors.

```javascript
const getUniqueCssSelector = (element) => {
  let result = '';
  let currentElement = element;

  const getNthChildSelector = (element) => {
    const parentElement = element.parentElement
    const siblings = Array.from(parentElement.children).filter(node => node instanceof Element)
    const elementIndex = siblings.indexOf(element) + 1;
    return `:nth-child(${elementIndex})`
  }

  while (currentElement && currentElement.parentElement) {
    const selector = getNthChildSelector(currentElement)
    result = element === currentElement ? selector : `${selector} > ${result}`;
    currentElement = currentElement.parentElement;
  }

  return `:root > ${result}`;
};
```
