### ISSUE TITLE
feature: Configurable attribute blacklist

### ISSUE THREAD

**Issue by danschalow** [fczbkk/css-selector-generator#50]
Attributes are currently blacklisted in a non-configurable value:

```javascript
export const ATTRIBUTE_BLACKLIST = convertMatchListToRegExp([
  'class',
  'id',
  // Angular attributes
  'ng-*',
]);
```

The values could be configured in the config object like:

```javascript
{
  attributeBlacklist: [
    'href', 
    'data-*',
  ]
}
```

Default values should be maintained, if no value is set.

**Comment by danschalow** [comment]
If you're interested in this feature, I would be happy to take care of it myself.

**Comment by fczbkk** [comment]
Thank you for the suggestion, @danschalow. But this config is private for a reason. It contains a list of attributes that should never be used when constructing an attribute selector. The class and ID are used by their respective selector types. The Angular attributes wreaked havoc in real-life scenarios.

You can easily blacklist the attribute selectors via (the `blacklist` option)[https://github.com/fczbkk/css-selector-generator#blacklist]. It will look something like this (I have added a lot of line breaks in an attempt to make all the brackets less confusing):

```javascript
getCssSelector(
  targetElement,
  { blacklist:
      [
        '[forbidden-attribute]'
      ]
  }
)
```

I think this can be resolved by making the documentation clearer, probably with better examples.

**Comment by fczbkk** [comment]
I have expanded the blacklist documentation:
https://github.com/fczbkk/css-selector-generator#blacklist

Let me know if that works for you. Thanks.

**Comment by danschalow** [comment]
Ah - perfect! That makes sense. Many thanks!
