### ISSUE TITLE
Add option to use -nth-child as little as possible

### ISSUE THREAD

**Issue by danieltroger** [fczbkk/css-selector-generator#51]
Hi,

I have the problem that your library falls back to something like this: `:nth-child(11) > :nth-child(2) > :nth-child(1) > :nth-child(9)` but what I need is a selector that goes as far as possible without using :nth-child, i.e. like this one: `div#__next > div.styles__MainContent-ghnxum-0.iIIhTW > div.styles__ContainerRoot-evpclk-2.kowoAH:nth-child(9)` because all the nth-child-numbers change during the pageload.

So the feature request would be to make as long selectors as possible without using nth-child. [This](https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/front_end/components/DOMPresentationUtils.js) is perfect for me but it outputs a selector matching multiple elements :(

I have tried those configuration options for your utility but it still prefers shortness over a sustainably working selector:

```
whitelist: ['class', 'tag', 'id', 'attribute'],
          combineWithinSelector: true,
          combineBetweenSelectors: true,
          includeTag: true
```

**Comment by jribbens** [comment]
I would like this too. Also I would like to be able to say that certain selectors are basically mandatory if they are available. e.g. if a document has only one `<link>` element, then asking for the selector for it just returns `link`, which is no use at all if later on someone adds another link. Having an option something like `mandatory: ["[href]", "[src]"]` to *require* the use of those attributes if they exist would be very helpful.

**Comment by alexferrari88** [comment]
+1

**Comment by fczbkk** [comment]
Hey guys, I just released `v3.0.0` which tries to use child selectors whenever possible. Please, give it a go. I think it will often produce simpler selectors, which should address this issue.

**Comment by jribbens** [comment]
Thanks. This does seem better, but it's still tending to come up with overly-short selectors like just `link`, or `.foo` or `[href="bar"]`... for my purposes I'd prefer to require at least two atoms in the selector, e.g. `link[href="baz"]` or `h2.foo` or `a[href="bar"]`.

**Comment by fczbkk** [comment]
@jribbens I'm closing this issue. What you describe in your comments seem to be out of scope of the original issue.

If what you describe still a thing for you, please open a new issue and describe in more detail how it should work and how the library should know when to add unnecessary parts of the selector. Thank you.
