### ISSUE TITLE
Issues on Facebook

### ISSUE THREAD

**Issue by lilacdev** [fczbkk/css-selector-generator#57]
Hello,

I am trying to use css-selector-generator on various websites through console. If I copy and paste build/index.js files in console, this works great :

`CssSelectorGenerator.getCssSelector($('body'))`
prints "body"

But on Facebook, when I do this, I get an error :
`Uncaught ReferenceError: CssSelectorGenerator is not defined`

I checked window and document objects, and, indeed, neither `CssSelectorGenerator` nor `getCssSelector` are defined.

Any idea about what could cause this issue ?

Many thanks,

**Comment by lilacdev** [comment]
Anyway, I used an extension to inject script. It is working now.

**Comment by fczbkk** [comment]
Hey @lilacdev, thank you for the report. I am able to replicate it too. It is strange. My guess is that Facebook uses some mechanism to prevent script injection (probably to stop attempts at XSS, scraping, etc.). I'm intrigued and I'll try to investigate further.

**Comment by lilacdev** [comment]
Indeed, I think it's a protection.
But I am not sure they can do much about protecting without controlling the browser.
I think that forcing window.CssSelectorGenerator attribution should do the trick (didn't had time to look in code source how global variable are managed). But according to my tests, this should do the trick.
