### ISSUE TITLE
xlink:href breaks getCSSSelector()

### ISSUE THREAD

**Issue by gradywetherbee** [fczbkk/css-selector-generator#580]
Finding a selector for this element causes errors:

`<use xlink:href="#help-bigger">`

> .vite-deps-css-selector-generator.js__v--f9fd6591.js:158 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '[xlink:href]' is not a valid selector.
>     at testSelector (chrome-extension://gnjkalklghjilkhfgcggjmflfigbjiem/vendor/.vite-deps-css-selector-generator.js__v--f9fd6591.js:158:61)
>     at getSelectorWithinRoot (chrome-extension://gnjkalklghjilkhfgcggjmflfigbjiem/vendor/.vite-deps-css-selector-generator.js__v--f9fd6591.js:486:9)
>     at getClosestIdentifiableParent (chrome-extension://gnjkalklghjilkhfgcggjmflfigbjiem/vendor/.vite-deps-css-selector-generator.js__v--f9fd6591.js:501:20)
>     at updateIdentifiableParent (chrome-extension://gnjkalklghjilkhfgcggjmflfigbjiem/vendor/.vite-deps-css-selector-generator.js__v--f9fd6591.js:577:12)
>     at getCssSelector (chrome-extension://gnjkalklghjilkhfgcggjmflfigbjiem/vendor/.vite-deps-css-selector-generator.js__v--f9fd6591.js:579:35)

When I tried blacklisting xlink:href as an attribute I still got an error with a similar trace:

`getCssSelector(el, { blacklist: ["[xlink:href]"]})`

> DOMException: Failed to execute 'querySelectorAll' on 'Document': '[xlink:href='\#help-bigger']' is not a valid selector.

Is there a proper way to handle this element with some options?

**Comment by fczbkk** [comment]
Hey @gradywetherbee, thanks for the report. The attribute names containing colons were not escaped.

I have released [`v3.6.6`](https://www.npmjs.com/package/css-selector-generator/v/3.6.6), which should contain the fix. Please update your dependency.
