### ISSUE TITLE
CssSelectorGenerator escapes the selector string

### ISSUE THREAD

**Issue by Danroyal001** [fczbkk/css-selector-generator#60]
CssSelectorGenerator escapes the selector string.

eg.

```javascript
3[src='https\3A \/\/site\.com\/folder\/file\.js']
```

instead of

```javascript
3[src='https://site.com/folder/file.js']
```

Is it possible to get the raw (unescaped) selector?

**Comment by roniemartinez** [comment]
I second this, the generated CSS is not a valid selector, especially with colon (`:`) which is cannot be unescaped.

```javascript
> unescape("3[src='https\3A \/\/site\.com\/folder\/file\.js']")

"3[src='https\u0003A //site.com/folder/file.js']"
```

**Comment by fczbkk** [comment]
@Danroyal001, @roniemartinez, can you please elaborate in more detail what you mean by your request?

I have checked the specification for attribute selectors:
https://www.w3.org/TR/selectors/#attribute-representation

The attribute selector's value should be a string token:
https://www.w3.org/TR/css-syntax-3/#typedef-string-token

Content of string tokens should be escaped. This diagram really helps to visualise the rules:
https://www.w3.org/TR/css-syntax-3/#string-token-diagram

So it looks like not escaping the attribute values in attribute selectors would lead to invalid selectors.

You can try to generate the correctly escaped value like this:

```javascript
CSS.escape("https://site.com/folder/file.js")
// "https\\:\\/\\/site\\.com\\/folder\\/file\\.js"
```

**Comment by roniemartinez** [comment]
@fczbkk I mean, for me, the generated selector is valid even if it is escaped but not colon and I have to do `replaceAll()` to make it a valid one:

```
getCssSelector(elements).replaceAll("\\3A", "\\\\3A")
```

`querySelector()` or jQuery is not accepting the generated selector for colon.

**Comment by fczbkk** [comment]
I see. So the escaping itself is not a problem. It's the way the colon character is escaped.

I have checked the code. There is special sequence used for colon. I think it's for compatibility with old browsers. But I'm not sure, I wrote that part very long ago.

I'll investigate. But I think I will replace the whole escaping logic with `CSS.escape`.

**Comment by fczbkk** [comment]
The old versions used escaping mechanism that was created to work with old versions of IE. The new version `v3.4.3` uses `CSS.escape()` instead. So there should be no longer special escape sequence used for colon.
