### ISSUE TITLE
IE 11 Syntax Error

### ISSUE THREAD

**Issue by HAMPLENI** [fczbkk/css-selector-generator#62]
I get a Syntax Error in IE 11 simply by including the following in my code:

`import getCssSelector from "css-selector-generator";`

The error prevents my page from loading.

I do not get the error in Chrome or Firefox.

**Comment by fczbkk** [comment]
@HAMPLENI Internet Explorer is an obsolete browser that does not support `import/export` syntax natively. If you want to use it, you have to use a bundler, e.g. [Webpack](https://webpack.js.org/).
