### ISSUE TITLE
Problem with generating common Multi-element selector

### ISSUE THREAD

**Issue by DiasKhalniyasov** [fczbkk/css-selector-generator#662]
I am trying to generate common selector for a list of elements:
`targets = '[data-snap-id="1949"],[data-snap-id="1999"],[data-snap-id="2042"]'`

My code:
```
let selector1 = await page.evaluate((selectors) => {
        // @ts-ignore
        return CssSelectorGenerator.getCssSelector(document.querySelectorAll(selectors), {
            blacklist: ["*snap*", "[style]"], selectors: ['id', 'class', 'tag', 'attributes'],
            combineWithinSelector: true, combineBetweenSelectors: true,
        });
    }, targets);
    console.log(selector1)
```
after adding combineWithinSelector  i still get a string of unique selectors like:
`._v3, .ListingCard:nth-child(3), .ListingCard:nth-child(4), .ListingCard:nth-child(5)`

if i blacklist 'nthchild' i get ugly selectors like :
`:root > :nth-child(2) > :nth-child(9) > :nth-child(1) > :nth-child(5) > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1)`

What i want to see is common selector like `div.ListingCard a.js-link`

Am I passing targets wrong? Should I use other way like passing root?

**Comment by fczbkk** [comment]
Hey @DiasKhalniyasov, can you please share the HTML from which you are trying to generate the selectors?

**Comment by DiasKhalniyasov** [comment]
i am trying to extract from this website:
https://www.jamesedition.com/real_estate/ibiza-spain

**Comment by fczbkk** [comment]
The library looks for **unique** CSS selectors for elements. That means, that the selector should target exactly the provided elements and no other elements.

I'm not sure which elements are you trying to target, I did not find any elements with attribute `data-snap-id` in the document. When I tried to target the elements by the first selector that you mentioned (`._v3, .ListingCard:nth-child(3), .ListingCard:nth-child(4), .ListingCard:nth-child(5)`), it returned exactly 4 elements. When I tried the selector that you expected (`div.ListingCard a.js-link`), it returned 30 elements. See the screenshot from console:

<img width="650" alt="Screenshot 2024-05-09 at 19 35 39" src="https://github.com/fczbkk/css-selector-generator/assets/43734/b640c241-6e95-4869-8e88-94a5a1ffca2d">

So, if you are looking for a selector that will target all these elements, you need to provide all these elements as input to the function.

I hope this helps. I'm closing this issue now. But feel free to reopen it and provide more information, if I did not get it right.
