### ISSUE TITLE
`3.0.1` Bundle Size Problem

### ISSUE THREAD

**Issue by joealden** [fczbkk/css-selector-generator#68]
As shown by https://bundlephobia.com/package/css-selector-generator, the bundle size of version 3.0.1 jumped significantly, this being because of the introduction of polyfills in f0b9d62.

Regarding this:

1. Should polyfilling this not be left up to the consumer, as otherwise, the consumer will be forced to use code they likely don't need to have (for my use case, I don't need any of these polyfills, so I will need to stay on `css-selector-generator@3.0.0`, or migrate to another library)?
2. Unless I am missing something, I think f0b9d62 results in a very large amount of `core-js` being included in the build (potentially all of it?), which very likely isn't necessary (see https://babeljs.io/docs/en/babel-preset-env for how to configure babel to only include the polyfills that are needed)?

---

Also, I believe that  https://github.com/fczbkk/css-selector-generator-benchmark#fczbkk-css-selector-generator is no longer correct for the following reasons:

1. This library does have dependencies.
2. This library is MIT licensed.

**Comment by fczbkk** [comment]
Yeah, you're right. The generators are not even needed. I was trying something and in the end I did it different way.

I will refactor it. Also, I should create separate builds for modern and old JS.

**Comment by fczbkk** [comment]
I have published `v3.1.0`. Removed all generators and polyfills. The bundle size went down significantly.

**Comment by joealden** [comment]
@fczbkk thanks!

Quick question, is there a reason that these changes don't exist on the `master` branch yet (which is currently the default branch)? I can see recent (published) changes on the `typescript` branch, but with them not on the default branch, you won't see the recent changes (including the changelog changes) on Github unless you look hard enough.

**Comment by fczbkk** [comment]
@joealden Yes. The reason is, that I was switched to the other branch and I didn't notice that I'm not in main branch. I have merged it, so now everything should be in a single main branch.
