### ISSUE TITLE
Get selector for multiple items

### ISSUE THREAD

**Issue by ducwp** [fczbkk/css-selector-generator#89]
```
<ul clas="nav-bar">
<li class="nav-item"><a href="#" class="nav">Item</a></li>
<li class="nav-item"><a href="#" class="nav">Item</a></li>
<li class="nav-item"><a href="#" class="nav">Item</a></li>
</ul>
```

I want to get: `ul.nav-bar > li.nav-item > a.nav` when I click on any a tag.

How to do it?

Thanks

**Comment by fczbkk** [comment]
@ducwp Looks like you are looking for a interactive selector builder. Something like (SelectorGadget)[https://selectorgadget.com/].
